---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: terraform-operator.vmware.com.0.0.1
spec:
  refName: terraform-operator.vmware.com
  version: "0.0.1"
  releaseNotes: |
        Initial release of the terraform-operator package
  licenses:
  - "Apache 2.0"
  releasedAt: 2023-01-25T04:40:00Z
  # valuesSchema:
  #   openAPIv3:
  #     title: terraform-operator.vmware.com values schema
  #     examples:
  #     - ingress_domain: shared.azure.grogscave.net
  #       ingress_secret: default/default-cert-tls
  #     properties:
  #       ingress_domain:
  #         type: string
  #         description: Top level ingress domain for cluster.  Will prepend "gitea" to the domain for ingress.
  #         examples:
  #         - shared.azure.grogscave.net
  #       ingress_secret:
  #         type: string
  #         description: Name of TLS secret to use with HTTPProxy.  Can be a delgated secret from another namespace.
  #         examples:
  #         - my-tls-secret
  #         - default/default-cert-tls
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: ghcr.io/cdelashmutt-pivotal/terraform-operator-package:0.0.1
      template:
      - ytt:
          paths:
          - "config/"
      - kbld:
          paths:
          - "-"
          - ".imgpkg/images.yml"
      deploy:
      - kapp: {}